# This file is normally generated by usethis::use_testthat() and
# shouldn't be edited by hand. It tells R CMD check how to run every
# test file in tests/testthat/ when the package is checked.
library(testthat)
library(ganbs.toolkit.demo)

test_check("ganbs.toolkit.demo")
